version: '3'

services:
  strapi:
    image: 'elestio/strapi-development:latest'
    environment:
      - SERVICE_FQDN_STRAPI_1337
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3307
      - 'DATABASE_NAME=${MYSQL_DATABASE:-strapi}'
      - DATABASE_USERNAME=$SERVICE_USER_MYSQL
      - DATABASE_PASSWORD=$SERVICE_PASSWORD_MYSQL
      - JWT_SECRET=$SERVICE_BASE64_64_SECRET
      - ADMIN_JWT_SECRET=$SERVICE_BASE64_64_SECRET
      - APP_KEYS=$SERVICE_BASE64_64_KEY
      - 'STRAPI_TELEMETRY_DISABLED=${STRAPI_TELEMETRY_DISABLED:-true}'
      - 'STRAPI_LICENSE=${STRAPI_LICENSE}'
      - 'NODE_ENV=${NODE_ENV:-development}'
      - 'BROWSER=${BROWSER:-true}'
      - 'STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE=${STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE:-en}'
      - 'STRAPI_ENFORCE_SOURCEMAPS=${STRAPI_ENFORCE_SOURCEMAPS:-false}'
      - 'FAST_REFRESH=${FAST_REFRESH:-true}'
    volumes:
      - 'strapi-app:/opt/app'
      - 'strapi-config:/opt/app/config'
      - 'strapi-src:/opt/app/src'
      - 'strapi-uploads:/opt/app/public/uploads'
    ports:
      - '1337:1337'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:1337/'
      interval: 5s
      timeout: 20s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-strapi}'
      - MYSQL_USER=$SERVICE_USER_MYSQL
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_MYSQL
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_MYSQL
    ports:
      - '3307:3306'
    volumes:
      - 'strapi-mysql-data:/var/lib/mysql'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
        - '-u'
        - root
        - '-p$$MYSQL_ROOT_PASSWORD'
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  strapi-app:
  strapi-config:
  strapi-src:
  strapi-uploads:
  strapi-mysql-data:
