name: Deploy to o2switch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Build backend
      run: |
        cd backend
        npm install
        npm run build

    - name: Deploy to o2switch
      run: |
        ssh o2switch "mkdir -p /home/grvi0340/siamkitchen-front/"
        ssh o2switch "mkdir -p /home/grvi0340/siamkitchen-back/"
        scp -r frontend/dist/* o2switch:/home/grvi0340/siamkitchen-front/
        scp -r backend/* o2switch:/home/grvi0340/siamkitchen-back/
